"""Guards for the learned stoplist.

`src/stoplist.py` is generated by `tools/build_stoplist.py` from the frozen
catalog. These tests assert the invariants that make the generated list safe to
ship, so a future regeneration - or a nudged threshold - fails loudly instead of
quietly deleting the signal the agent runs on.
"""

from __future__ import annotations

import unittest

from src.stoplist import SCAFFOLDING
from src.text import BOILERPLATE, CARE_PHRASES, STOPWORDS, terms


# The simulated customer's constraints are built by `intent_card()`, which inserts
# a material at position 0 and a colour at position 1 of every card. Stripping any
# of these from a query would remove the most reliable signal in the protocol.
ATTRIBUTE_WORDS = (
    "cotton", "polyester", "leather", "nylon", "spandex", "wool", "silk",
    "black", "white", "blue", "red", "pink", "steel", "silver", "gold",
    "waterproof", "buckle", "sleeve", "zipper", "heel", "sole",
)

# Amazon's structural metadata keys, which appear in tens of thousands of products
# regardless of what the product is.
SCAFFOLDING_WORDS = (
    "department", "dimensions", "manufacturer", "ounces", "date", "available",
    "inches", "package", "model", "number", "discontinued", "pounds",
)

# Care-and-origin phrases that no catalog statistic separates from real attribute
# words; see the note in src/text.py.
HAND_WRITTEN_WORDS = ("imported", "machine", "wash", "closure", "care", "asin")


class StoplistContentTests(unittest.TestCase):
    def test_attribute_words_are_never_stripped(self) -> None:
        for word in ATTRIBUTE_WORDS:
            with self.subTest(word=word):
                self.assertNotIn(word, BOILERPLATE)
                self.assertNotIn(word, STOPWORDS)

    def test_structural_metadata_is_stripped(self) -> None:
        for word in SCAFFOLDING_WORDS:
            with self.subTest(word=word):
                self.assertIn(word, SCAFFOLDING)

    def test_hand_written_remainder_survives_regeneration(self) -> None:
        # These are unreachable by the generator's rule, so they must live in
        # CARE_PHRASES or regenerating the stoplist would silently drop them.
        for word in HAND_WRITTEN_WORDS:
            with self.subTest(word=word):
                self.assertIn(word, CARE_PHRASES)
                self.assertIn(word, BOILERPLATE)

    def test_date_scaffolding_was_learned(self) -> None:
        # "Date First Available: August 15, 2019" - months and years the
        # hand-written list never covered.
        for word in ("january", "august", "december", "2014", "2019", "2022"):
            with self.subTest(word=word):
                self.assertIn(word, SCAFFOLDING)

    def test_the_two_halves_are_disjoint_and_clear_of_stopwords(self) -> None:
        self.assertEqual(SCAFFOLDING & CARE_PHRASES, frozenset())
        self.assertEqual(BOILERPLATE & STOPWORDS, frozenset())
        self.assertEqual(BOILERPLATE, SCAFFOLDING | CARE_PHRASES)


class StoplistBehaviourTests(unittest.TestCase):
    def test_scaffolding_is_dropped_from_a_disclosed_constraint(self) -> None:
        # A shipping-dimensions constraint reduces to nothing: every word is
        # scaffolding and the bare digits fall under the two-character floor.
        message = "For that, what matters is: Package Dimensions 9 x 4 x 1 inches; 6 Ounces."
        self.assertEqual(terms(message, drop_boilerplate=True), [])

    def test_a_material_constraint_survives_intact(self) -> None:
        message = "For that, what matters is: 96% Nylon, 4% Spandex; Pull-On closure."
        kept = terms(message, drop_boilerplate=True)
        self.assertIn("nylon", kept)
        self.assertIn("spandex", kept)
        self.assertNotIn("closure", kept)


if __name__ == "__main__":
    unittest.main()
